#!/bin/bash

ssh -t amazoncv@192.168.88.245 "/home/amazoncv/catkin_ws/src/ros-eurobot-2018/eurobot/kill_nodes"
ssh -t amazoncv@192.168.88.245 "fuser -k /dev/video0"
ssh -t amazoncv@192.168.88.245 "fuser -k /dev/video1"
ssh -f amazoncv@192.168.88.245 "screen -d -m /home/amazoncv/catkin_ws/src/ros-eurobot-2018/eurobot/green"
sleep 10s

export ROS_MASTER_URI=http://192.168.88.245:11311
roslaunch eurobot_sim visualization.launch