#!/bin/bash

source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash
export ROS_IP=192.168.88.244
export DISPLAY=:0.0
sleep 1s
while true; do
    roslaunch eurobot main_robot.launch color:=$1
    sleep 1s
done
