#!/bin/bash

ssh -t amazoncv@192.168.88.245 "~/catkin_ws/src/ros-eurobot-2018/eurobot/kill_nodes"
ssh -t amazoncv@192.168.88.245 "screen -d -S '/home/pi/catkin_ws/src/ros-eurobot-2018/eurobot/orange'"