#!/bin/bash
date1=`python2 /home/odroid/catkin_ws/src/ros-eurobot-2018/scripts/make_older.py`
date +%Y%m%d%T -s $date1
source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash
#export ROS_IP=192.168.88.242
sleep 1s
while true; do
    roslaunch eurobot secondary_robot.launch color:=$1
    sleep 1s
done
