#!/bin/bash

source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash
export ROS_IP=192.168.88.242
sleep 1s
while true; do
    roslaunch eurobot secondary_robot_orange.launch
    sleep 1s
done

