obstacle_range: 0.5
raytrace_range: 3.0
footprint: [[0.21, 0.095], [0.21, -0.095], [-0.21, -0.095], [-0.21, 0.095], 
[-0.11, 0.095], [-0.11, -0.045], [0.11, -0.045], [0.11, 0.095]]
#robot_radius: ir_of_robot
#robot_radius: 0.22 # distance a circular robot should be clear of the obstacle
#inflation_radius: 3.0

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /mybot/laser/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
