footprint: [[0.21, 0.095], [0.21, -0.095], [-0.21, -0.095], [-0.21, 0.095], 
[-0.11, 0.095], [-0.11, -0.045], [0.11, -0.045], [0.11, 0.095]]
#robot_radius: ir_of_robot
#robot_radius: 0.22 # distance a circular robot should be clear of the obstacle
cost_scaling_factor: 30
inflation_radius: 0.2
resolution: 0.01
robot_base_frame: main_robot
global_frame: /map
