base_local_planner: "dwa_local_planner/DWAPlannerROS"

controller_frequency: 10.0      # 20.0
controller_patience:  15.0      # 15.0

DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 3
  acc_lim_y: 3
  acc_lim_theta: 6

  max_trans_vel: 3
  min_trans_vel: 0.005

  max_vel_x: 0.5
  min_vel_x: -0.5 #0.005

  max_vel_y: 0.5
  min_vel_y: -0.5 #0.005

  max_rot_vel: 2.7
  min_rot_vel: -2.7 #0.03

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.03 
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.5
  sim_granularity: 0.02
  vx_samples: 10
  vy_samples: 10
  vth_samples: 10
  controller_frequency: 10

  # Trajectory Scoring Parameters
  path_distance_bias: 30
  goal_distance_bias: 30
  occdist_scale: 0.05
  forward_point_distance: 0.15
  stop_time_buffer: 0.1
  scaling_speed: 0.25
  max_scaling_factor: 0.5 # ???

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 

  # Global Plan Parameters
  prune_plan: true

