visualize_potential: true
global_frame: /map
update_frequency: 30
publish_frequency: 30
width: 3.0
height: 2.0
resolution: 0.01
plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
inflation_layer:
    cost_scaling_factor: 30
    inflation_radius: 0.5
    
