visualize_potential: true
global_frame: /map
update_frequency: 30
publish_frequency: 30
width: 3.0
height: 2.0
resolution: 0.01
plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: social_layer,        type: "social_navigation_layers::ProxemicLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
social_layer:
    cutoff: 1
    amplitude: 254
    covariance: 0.1
    #factor: 5.0
    #keep_time: 0.75
inflation_layer:
    cost_scaling_factor: 30
    inflation_radius: 0.5
    
