local_costmap:
    robot_radius: 0.222
    cost_scaling_factor: 30
    inflation_radius: 0.5
    resolution: 0.01
    robot_base_frame: main_robot
    global_frame: /map
    update_frequency: 0.1
    publish_frequency: 0.1
    static_map: true
    rolling_window: false
    width: 3.0
    height: 2.0
